### ISSUE TITLE
Error after upgrading to PHPStorm 2017.1

### ISSUE THREAD

**Issue by ikerasLT** [Haehnchen/idea-php-laravel-plugin#135]
```
Error while indexing /Users/marius/PhpstormProjects/smarttaxi_api_laravel/app/Http/routes.php
To reindex this file IDEA has to be restarted: -1
java.lang.ArrayIndexOutOfBoundsException: -1
	at de.espend.idea.laravel.routing.utils.RoutingUtil$RouteNamePsiRecursiveElementVisitor.visitResource(RoutingUtil.java:214)
	at de.espend.idea.laravel.routing.utils.RoutingUtil$RouteNamePsiRecursiveElementVisitor.visitElement(RoutingUtil.java:145)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:33)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at de.espend.idea.laravel.routing.utils.RoutingUtil$RouteNamePsiRecursiveElementVisitor.visitElement(RoutingUtil.java:151)
	at com.jetbrains.php.lang.psi.elements.impl.StatementImpl.accept(StatementImpl.java:24)
	at com.intellij.psi.impl.source.tree.LazyParseablePsiElement.acceptChildren(LazyParseablePsiElement.java:106)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at de.espend.idea.laravel.routing.utils.RoutingUtil$RouteNamePsiRecursiveElementVisitor.visitElement(RoutingUtil.java:151)
	at com.jetbrains.php.lang.psi.elements.impl.GroupStatementImpl.accept(GroupStatementImpl.java:30)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at de.espend.idea.laravel.routing.utils.RoutingUtil$RouteNamePsiRecursiveElementVisitor.visitElement(RoutingUtil.java:151)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:73)
	at com.jetbrains.php.lang.psi.elements.impl.FunctionImpl.accept(FunctionImpl.java:118)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at de.espend.idea.laravel.routing.utils.RoutingUtil$RouteNamePsiRecursiveElementVisitor.visitElement(RoutingUtil.java:151)
	at com.jetbrains.php.lang.psi.elements.impl.PhpExpressionImpl.accept(PhpExpressionImpl.java:43)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at de.espend.idea.laravel.routing.utils.RoutingUtil$RouteNamePsiRecursiveElementVisitor.visitElement(RoutingUtil.java:151)
	at com.jetbrains.php.lang.psi.elements.impl.ParameterListImpl.accept(ParameterListImpl.java:33)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at de.espend.idea.laravel.routing.utils.RoutingUtil$RouteNamePsiRecursiveElementVisitor.visitElement(RoutingUtil.java:151)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:33)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at de.espend.idea.laravel.routing.utils.RoutingUtil$RouteNamePsiRecursiveElementVisitor.visitElement(RoutingUtil.java:151)
	at com.jetbrains.php.lang.psi.elements.impl.StatementImpl.accept(StatementImpl.java:24)
	at com.intellij.psi.impl.source.tree.LazyParseablePsiElement.acceptChildren(LazyParseablePsiElement.java:106)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at de.espend.idea.laravel.routing.utils.RoutingUtil$RouteNamePsiRecursiveElementVisitor.visitElement(RoutingUtil.java:151)
	at com.jetbrains.php.lang.psi.elements.impl.GroupStatementImpl.accept(GroupStatementImpl.java:30)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at de.espend.idea.laravel.routing.utils.RoutingUtil$RouteNamePsiRecursiveElementVisitor.visitElement(RoutingUtil.java:151)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:73)
	at com.jetbrains.php.lang.psi.elements.impl.FunctionImpl.accept(FunctionImpl.java:118)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at de.espend.idea.laravel.routing.utils.RoutingUtil$RouteNamePsiRecursiveElementVisitor.visitElement(RoutingUtil.java:151)
	at com.jetbrains.php.lang.psi.elements.impl.PhpExpressionImpl.accept(PhpExpressionImpl.java:43)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at de.espend.idea.laravel.routing.utils.RoutingUtil$RouteNamePsiRecursiveElementVisitor.visitElement(RoutingUtil.java:151)
	at com.jetbrains.php.lang.psi.elements.impl.ParameterListImpl.accept(ParameterListImpl.java:33)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at de.espend.idea.laravel.routing.utils.RoutingUtil$RouteNamePsiRecursiveElementVisitor.visitElement(RoutingUtil.java:151)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:33)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at de.espend.idea.laravel.routing.utils.RoutingUtil$RouteNamePsiRecursiveElementVisitor.visitElement(RoutingUtil.java:151)
	at com.jetbrains.php.lang.psi.elements.impl.StatementImpl.accept(StatementImpl.java:24)
	at com.intellij.psi.impl.source.tree.LazyParseablePsiElement.acceptChildren(LazyParseablePsiElement.java:106)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at de.espend.idea.laravel.routing.utils.RoutingUtil$RouteNamePsiRecursiveElementVisitor.visitElement(RoutingUtil.java:151)
	at com.jetbrains.php.lang.psi.elements.impl.GroupStatementImpl.accept(GroupStatementImpl.java:30)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at de.espend.idea.laravel.routing.utils.RoutingUtil$RouteNamePsiRecursiveElementVisitor.visitElement(RoutingUtil.java:151)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:73)
	at com.jetbrains.php.lang.psi.elements.impl.FunctionImpl.accept(FunctionImpl.java:118)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at de.espend.idea.laravel.routing.utils.RoutingUtil$RouteNamePsiRecursiveElementVisitor.visitElement(RoutingUtil.java:151)
	at com.jetbrains.php.lang.psi.elements.impl.PhpExpressionImpl.accept(PhpExpressionImpl.java:43)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at de.espend.idea.laravel.routing.utils.RoutingUtil$RouteNamePsiRecursiveElementVisitor.visitElement(RoutingUtil.java:151)
	at com.jetbrains.php.lang.psi.elements.impl.ParameterListImpl.accept(ParameterListImpl.java:33)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at de.espend.idea.laravel.routing.utils.RoutingUtil$RouteNamePsiRecursiveElementVisitor.visitElement(RoutingUtil.java:151)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:33)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at de.espend.idea.laravel.routing.utils.RoutingUtil$RouteNamePsiRecursiveElementVisitor.visitElement(RoutingUtil.java:151)
	at com.jetbrains.php.lang.psi.elements.impl.StatementImpl.accept(StatementImpl.java:24)
	at com.intellij.psi.impl.source.tree.LazyParseablePsiElement.acceptChildren(LazyParseablePsiElement.java:106)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at de.espend.idea.laravel.routing.utils.RoutingUtil$RouteNamePsiRecursiveElementVisitor.visitElement(RoutingUtil.java:151)
	at com.jetbrains.php.lang.psi.elements.impl.GroupStatementImpl.accept(GroupStatementImpl.java:30)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at de.espend.idea.laravel.routing.utils.RoutingUtil$RouteNamePsiRecursiveElementVisitor.visitElement(RoutingUtil.java:151)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.jetbrains.php.lang.psi.elements.impl.PhpPsiElementImpl.accept(PhpPsiElementImpl.java:73)
	at com.jetbrains.php.lang.psi.elements.impl.FunctionImpl.accept(FunctionImpl.java:118)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at de.espend.idea.laravel.routing.utils.RoutingUtil$RouteNamePsiRecursiveElementVisitor.visitElement(RoutingUtil.java:151)
	at com.jetbrains.php.lang.psi.elements.impl.PhpExpressionImpl.accept(PhpExpressionImpl.java:43)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at de.espend.idea.laravel.routing.utils.RoutingUtil$RouteNamePsiRecursiveElementVisitor.visitElement(RoutingUtil.java:151)
	at com.jetbrains.php.lang.psi.elements.impl.ParameterListImpl.accept(ParameterListImpl.java:33)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at de.espend.idea.laravel.routing.utils.RoutingUtil$RouteNamePsiRecursiveElementVisitor.visitElement(RoutingUtil.java:151)
	at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:33)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at de.espend.idea.laravel.routing.utils.RoutingUtil$RouteNamePsiRecursiveElementVisitor.visitElement(RoutingUtil.java:151)
	at com.jetbrains.php.lang.psi.elements.impl.StatementImpl.accept(StatementImpl.java:24)
	at com.intellij.psi.impl.PsiElementBase.acceptChildren(PsiElementBase.java:69)
	at com.intellij.psi.PsiRecursiveElementVisitor.visitElement(PsiRecursiveElementVisitor.java:40)
	at de.espend.idea.laravel.routing.utils.RoutingUtil$RouteNamePsiRecursiveElementVisitor.visitElement(RoutingUtil.java:151)
	at com.jetbrains.php.lang.psi.elements.impl.GroupStatementSimpleImpl.accept(GroupStatementSimpleImpl.java:28)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:857)
	at de.espend.idea.laravel.routing.utils.RoutingUtil.visitRoutesForAs(RoutingUtil.java:99)
	at de.espend.idea.laravel.routing.utils.RoutingUtil.getRoutesAsNames(RoutingUtil.java:91)
	at de.espend.idea.laravel.stub.RouteIndexExtension.lambda$getIndexer$0(RouteIndexExtension.java:42)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:251)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.calculateUpdateData(VfsAwareMapReduceIndex.java:96)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:194)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1582)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1518)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:516)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1479)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1464)
	at com.intellij.util.indexing.UnindexedFilesUpdater.a(UnindexedFilesUpdater.java:105)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:229)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:246)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:242)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by adelf** [comment]
Already fixed by #131 . Will be in the next release.
