### ISSUE TITLE
IDE Fatal Error in phpstorn 2019.2.4

### ISSUE THREAD

**Issue by nontakan-doae** [Haehnchen/idea-php-laravel-plugin#247]
com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.css.impl.CssTokenImpl #CSS  because: VirtualFileWindow in D:\Source_code\DOAE\nature\resources\views\profile\index.blade.php is invalid
invalidated at: see attachment; com.intellij.psi.css.impl.CssTokenImpl:CSS_HASH / com.intellij.psi.impl.source.tree.CompositeElement:PsiElement(CSS_ID_SELECTOR) / com.intellij.psi.css.impl.CssSelectorSuffixListImpl:CSS_SELECTOR_SUFFIX_LIST / com.intellij.psi.impl.source.tree.CompositeElement:PsiElement(CSS_SIMPLE_SELECTOR) / com.intellij.psi.impl.source.tree.CompositeElement:PsiElement(CSS_SELECTOR) / com.intellij.psi.impl.source.tree.CompositeElement:PsiElement(CSS_SELECTOR_LIST) / com.intellij.psi.impl.source.tree.CompositeElement:PsiElement(CSS_RULESET) / com.intellij.psi.impl.source.tree.CompositeElement:PsiElement(CSS_RULESET_LIST) / com.intellij.psi.impl.source.tree.CompositeElement:PsiElement(JQUERY_CSS_STYLESHEET) / com.intellij.psi.css.impl.CssLazyStylesheet:JQUERY_CSS_LAZY_STYLESHEET / com.intellij.psi.impl.source.tree.FileElement:JQUERY_CSS_FILE
	at com.intellij.psi.impl.source.tree.LeafPsiElement.invalid(LeafPsiElement.java:103)
	at com.intellij.psi.impl.source.tree.LeafPsiElement.getContainingFile(LeafPsiElement.java:87)
	at com.intellij.patterns.PsiElementPattern$3.accepts(PsiElementPattern.java:143)
	at com.intellij.patterns.PsiElementPattern$3.accepts(PsiElementPattern.java:140)
	at com.intellij.patterns.ObjectPattern.accepts(ObjectPattern.java:61)
	at com.intellij.patterns.ObjectPattern.accepts(ObjectPattern.java:50)
	at fr.adrienbrault.idea.symfony2plugin.codeInsight.utils.GotoCompletionUtil.lambda$getContributors$0(GotoCompletionUtil.java:39)
	at de.espend.idea.laravel.blade.BladeDirectiveReferences.register(BladeDirectiveReferences.java:64)
	at fr.adrienbrault.idea.symfony2plugin.codeInsight.utils.GotoCompletionUtil.getContributors(GotoCompletionUtil.java:51)
	at fr.adrienbrault.idea.symfony2plugin.codeInsight.completion.CompletionContributor$1.addCompletions(CompletionContributor.java:30)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:40)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:150)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:63)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:148)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:141)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$1.addCompletions(LiveTemplateCompletionContributor.java:77)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:40)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:150)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:63)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:119)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.performCompletion(CompletionServiceImpl.java:55)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:824)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:809)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$5(CodeCompletionHandlerBase.java:325)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$tryReadOrCancel$5(CompletionThreading.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:170)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$6(CodeCompletionHandlerBase.java:317)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by armen9494** [comment]
I have the same issue
