### ISSUE TITLE
Plugin ClassCastException when using associate method in laravel

### ISSUE THREAD

**Issue by mirageisme** [Haehnchen/idea-php-laravel-plugin#60]
Every time I use the model associate method the plugin crashes for example:

        $post = Auth::user()->posts()->create($data);
        $post->app()->associate($app)->save();
        $post->media()->save($media);

and in the Post class:

    public function app()
    {
        return $this->belongsTo('App\App');
    }

The event log:

	com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl cannot be cast to com.jetbrains.php.lang.psi.elements.impl.FunctionReferenceImpl
	java.lang.ClassCastException: com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl cannot be cast to com.jetbrains.php.lang.psi.elements.impl.FunctionReferenceImpl
		at de.espend.idea.laravel.dic.DicTypeProvider.getType(DicTypeProvider.java:45)
		at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:43)
		at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:37)
		at com.intellij.openapi.util.Computable$NotNullCachedComputable.compute(Computable.java:52)
		at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
		at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
		at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getType(PhpTypeInfo.java:37)
		at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.getType(PhpReferenceImpl.java:207)
		at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.resolveGlobal(MemberReferenceImpl.java:144)
		at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl$1.resolve(PhpReferenceImpl.java:144)
		at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl$1.resolve(PhpReferenceImpl.java:141)
		at com.intellij.psi.impl.source.resolve.ResolveCache$3.compute(ResolveCache.java:142)
		at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
		at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:139)
		at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
		at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
		at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.multiResolve(PhpReferenceImpl.java:136)
		at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.resolve(PhpReferenceImpl.java:122)
		at com.jetbrains.php.lang.annotator.PhpAnnotatorVisitor.checkAccessModifiers(PhpAnnotatorVisitor.java:411)
		at com.jetbrains.php.lang.annotator.PhpAnnotatorVisitor.visitPhpMethodReference(PhpAnnotatorVisitor.java:393)
		at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:29)
		at com.jetbrains.php.lang.annotator.PhpAnnotator.annotate(PhpAnnotator.java:19)
		at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:135)
		at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:99)
		at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:351)
		at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$100(GeneralHighlightingPass.java:62)
		at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$3.run(GeneralHighlightingPass.java:285)
		at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:305)
		at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$200(GeneralHighlightingPass.java:62)
		at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$4.run(GeneralHighlightingPass.java:311)
		at com.intellij.codeInsight.daemon.impl.analysis.XmlHighlightVisitor.analyze(XmlHighlightVisitor.java:750)
		at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:308)
		at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$200(GeneralHighlightingPass.java:62)
		at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$4.run(GeneralHighlightingPass.java:311)
		at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:83)
		at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:308)
		at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:277)
		at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:216)
		at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
		at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
		at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
		at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
		at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
		at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
		at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
		at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
		at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
		at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
		at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
		at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
		at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
		at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
		at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)

	java.lang.ClassCastException: com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl cannot be cast to com.jetbrains.php.lang.psi.elements.impl.FunctionReferenceImpl
		at de.espend.idea.laravel.dic.DicTypeProvider.getType(DicTypeProvider.java:45)
		at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:43)
		at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo$1.internalCompute(PhpTypeInfo.java:37)
		at com.intellij.openapi.util.Computable$NotNullCachedComputable.compute(Computable.java:52)
		at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
		at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
		at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getType(PhpTypeInfo.java:37)
		at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.getType(PhpReferenceImpl.java:207)
		at com.jetbrains.php.lang.psi.elements.impl.MemberReferenceImpl.resolveGlobal(MemberReferenceImpl.java:144)
		at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl$1.resolve(PhpReferenceImpl.java:144)
		at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl$1.resolve(PhpReferenceImpl.java:141)
		at com.intellij.psi.impl.source.resolve.ResolveCache$3.compute(ResolveCache.java:142)
		at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:112)
		at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:139)
		at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
		at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
		at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.multiResolve(PhpReferenceImpl.java:136)
		at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.resolve(PhpReferenceImpl.java:122)
		at com.jetbrains.php.lang.inspections.PhpMethodParametersCountMismatchInspection$1.inspect(PhpMethodParametersCountMismatchInspection.java:40)
		at com.jetbrains.php.lang.inspections.PhpMethodParametersCountMismatchInspection$1.visitPhpMethodReference(PhpMethodParametersCountMismatchInspection.java:94)
		at com.jetbrains.php.lang.psi.elements.impl.MethodReferenceImpl.accept(MethodReferenceImpl.java:29)
		at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
		at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:320)
		at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:315)
		at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:128)
		at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
		at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:91)
		at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
		at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:100)
		at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
		at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
		at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
		at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
		at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:112)
		at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:88)
		at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
		at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
		at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
		at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
		at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
		at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)

**Comment by Haehnchen** [comment]
duplicates #54
