### ISSUE TITLE
Plugin throws java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by metasoftware** [Haehnchen/idea-php-laravel-plugin#64]
![screenshot_2016-06-20_00-00-26](https://cloud.githubusercontent.com/assets/3266470/16180329/03691f5e-367a-11e6-8142-dd5d6d9b4ce1.png)

Updated to 0.10 and got the above error, I invalidated caches, disabled and re-enabled as well as installed from scratch still getting the error.

Please advise if there is anything else you'd like me to try, the plugin seems to work ok even with the error so far however it throws it *a lot* several dozen times in a few minutes.

Running Intellij IDEA 2016.1.3 with the bundled JDK on Xubuntu 16.04.

**Comment by Kurre** [comment]
Same happens with:

> PhpStorm 2016.2 EAP
> Build #PS-162.917.12, built on June 15, 2016
> PhpStorm EAP User
> Expiration date: July 15, 2016
> JRE: 1.8.0_76-release-b216 x86
> JVM: OpenJDK Server VM by JetBrains s.r.o

Running on Windows 7.

Happends when you open Blade template file.
Opening some class, composer.json, etc doesn't trigger this error.

dump:

```
2016-06-20 09:01:03,854 [ 574271]  ERROR - aemon.impl.PassExecutorService - null 
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
	at de.espend.idea.laravel.blade.TemplateLineMarker.collectTemplateFileRelatedFiles(TemplateLineMarker.java:139)
	at de.espend.idea.laravel.blade.TemplateLineMarker.collectSlowLineMarkers(TemplateLineMarker.java:65)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.addLineMarkers(SlowLineMarkersPass.java:78)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.doCollectInformation(SlowLineMarkersPass.java:65)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1033)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:425)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:424)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:400)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:154)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2016-06-20 09:01:03,856 [ 574273]  ERROR - aemon.impl.PassExecutorService - PhpStorm 2016.2 EAP  Build #PS-162.917.12 
2016-06-20 09:01:03,857 [ 574274]  ERROR - aemon.impl.PassExecutorService - JDK: 1.8.0_76-release 
2016-06-20 09:01:03,857 [ 574274]  ERROR - aemon.impl.PassExecutorService - VM: OpenJDK Server VM 
2016-06-20 09:01:03,857 [ 574274]  ERROR - aemon.impl.PassExecutorService - Vendor: JetBrains s.r.o 
2016-06-20 09:01:03,857 [ 574274]  ERROR - aemon.impl.PassExecutorService - OS: Windows 7 
2016-06-20 09:01:03,858 [ 574275]  ERROR - aemon.impl.PassExecutorService - null 
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
	at de.espend.idea.laravel.blade.TemplateLineMarker.collectTemplateFileRelatedFiles(TemplateLineMarker.java:139)
	at de.espend.idea.laravel.blade.TemplateLineMarker.collectSlowLineMarkers(TemplateLineMarker.java:65)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.addLineMarkers(SlowLineMarkersPass.java:78)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.doCollectInformation(SlowLineMarkersPass.java:65)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1033)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:425)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:424)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:400)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:154)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2016-06-20 09:01:03,859 [ 574276]  ERROR - aemon.impl.PassExecutorService - PhpStorm 2016.2 EAP  Build #PS-162.917.12 
2016-06-20 09:01:03,859 [ 574276]  ERROR - aemon.impl.PassExecutorService - JDK: 1.8.0_76-release 
2016-06-20 09:01:03,859 [ 574276]  ERROR - aemon.impl.PassExecutorService - VM: OpenJDK Server VM 
2016-06-20 09:01:03,860 [ 574277]  ERROR - aemon.impl.PassExecutorService - Vendor: JetBrains s.r.o 
2016-06-20 09:01:03,860 [ 574277]  ERROR - aemon.impl.PassExecutorService - OS: Windows 7 
```

**Comment by Haehnchen** [comment]
fixed

**Comment by metasoftware** [comment]
You work quickly!, also thank you very much for the work on your plugin, it makes Laravel development even more pleasant :).
