### ISSUE TITLE
NPE on 0.12.2

### ISSUE THREAD

**Issue by maghetto85** [Haehnchen/idea-php-laravel-plugin#96]
Hi, the NPE error is still present in new release

PhpStorm Version 2016.3.2
OS Windows 7

````
null
java.lang.NullPointerException
	at de.espend.idea.laravel.controller.ControllerReferences$2.getArrayMethodParameter(ControllerReferences.java:188)
	at de.espend.idea.laravel.controller.ControllerReferences$2.getProvider(ControllerReferences.java:172)
	at fr.adrienbrault.idea.symfony2plugin.codeInsight.navigation.GotoHandler.getGotoDeclarationTargets(GotoHandler.java:31)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:292)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findAllTargetElements(GotoDeclarationAction.java:279)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.a(GotoDeclarationAction.java:92)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:899)
	at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.a(GotoDeclarationAction.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$11.run(CoreProgressManager.java:423)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:572)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
````

**Comment by Haehnchen** [comment]
please check against `0.12.3`

**Comment by maghetto85** [comment]
seems ok! Good Work!
